#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config status_bar                   on

yabai -m config status_bar_background_color  0xff354274 # 0xff202020
yabai -m config status_bar_foreground_color  0xffDEE6E7 # 0xffa8a8a8

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

# visual
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config window_shadow float
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.8
yabai -m config split_ratio                  0.6
yabai -m config auto_balance                 off

# bar settings
## add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar all:32:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   10

# mouse
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize


# Spaces
yabai -m space 1 --label "Coding"
yabai -m space 2 --label "Typing"
yabai -m space 3 --label "Tools"
yabai -m space 4 --label "Social"
yabai -m space 5 --label "Float"

# Coding

# Tools
yabai -m rule --add app="^Books$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^macfeh$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on

# Social
yabai -m rule --add app="Telegram" scratchpad="telegram" grid=11:11:1:1:9:9
yabai -m rule --add app="Obsidian" scratchpad="obsidian" grid=1:1:0:0:1:1
yabai -m rule --add app="DeepL" scratchpad="deepl" grid=11:11:1:1:9:9
yabai -m rule --add app="Calendar" scratchpad="calendar" grid=11:11:1:1:9:9
yabai -m rule --add app="Open WebUI" scratchpad="openwebui" grid=11:11:1:1:9:9
yabai -m rule --add app="Vivaldi" scratchpad="browser" grid=1:1:0:0:1:1
yabai -m rule --add app="Yandex Music" scratchpad="music" grid=11:11:6:0:5:7
# yabai -m rule --add app="Alacritty" scratchpad="console" grid=1:1:0:0:1:1
yabai -m rule --add title="console" scratchpad="console" grid=1:1:0:0:1:1

yabai -m rule --add app="^Mail$" space=4

# Floating applications that don't need to manage
# System utilities
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Console$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off

# File operations
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^The Unarchiver$" manage=off
yabai -m rule --add app="^Transmission$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off

# Browsers and specific windows
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^App Store$" manage=off

# Utilities and tools
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Telephone" sticky=on manage=off
yabai -m rule --add app="^eqMac$" manage=off
yabai -m rule --add app="^VirtualBox$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Font Book$" manage=off



echo "yabai configuration loaded.."
