#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config status_bar                   on

yabai -m config status_bar_background_color  0xff354274 # 0xff202020
yabai -m config status_bar_foreground_color  0xffDEE6E7 # 0xffa8a8a8

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config window_opacity               on
yabai -m config active_window_opacity        0.5
yabai -m config normal_window_opacity        0.9
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                resize
yabai -m config mouse_action2                move

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  26
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# Spaces
yabai -m space 1 --label "Coding"
yabai -m space 2 --label "Typing"
yabai -m space 3 --label "Tools"
yabai -m space 4 --label "Social"
yabai -m space 5 --label "Float"

# Coding

# Tools
yabai -m rule --add app="^GitHub Desktop$" manage=off space=3
yabai -m rule --add app="Sourcetree"            space=3
yabai -m rule --add app="Finder"                space=3
yabai -m rule --add app="Microsoft Word"        space=3
yabai -m rule --add app="Sequel Pro"            space=3
yabai -m rule --add app="Postman"               space=3

yabai -m rule --add app="^System Preferences$" manage=off grid=7:4:1:1:2:2
yabai -m rule --add app="^Books$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^macfeh$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on

# Social
yabai -m rule --add app="^Zoom$" manage=off space=4
yabai -m rule --add app="^zoom.us$" space=4
yabai -m rule --add app="^Telegram$" space=4
yabai -m rule --add app="^Mail$" space=4

# Floating
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^Telephone" sticky=on manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off
yabai -m rule --add label="eqMac" app="^eqMac$" manage=off



echo "yabai configuration loaded.."


