#!/bin/sh

# Open screen connection to choosen tty 
title=$1 || "TTY Selection"
# Get user selection via dmenu from /dev/tty.*
ttys=$(ls -1 /dev/tty.* | cat -n)
chosen=$(dialog --title "$title" \
  --menu "Serial port:" 10 40 4 \
  ${ttys} 3>&1 1>&2 2>&3 3>&1)
chosen=$(echo "$ttys" | sed -n ${chosen}p | cut -d$'\t' -f2)

# Exit if none chosen.
[ -z "$chosen" ] && exit

baudrates="1 115200 2 9600"
baudrate=$(dialog --backtitle "TTY Baudrate Selection" \
  --menu "Baudrate:" 10 40 4 \
  ${baudrates} 3>&1 1>&2 2>&3 3>&1)
baudrate=$(expr $baudrate \* 2)
baudrate=$(echo $baudrates | cut -d' ' -f$baudrate)
echo $chosen $baudrate
