#!/bin/sh

# Open screen connection to choosen tty

# Get user selection via dmenu from /dev/tty.*
bookmarks=$(echo `pbpaste` | cat - ~/.config/bookmarks.youtube.url)
request=$(echo "$bookmarks" | xmenu -i -fn "FiraCode Nerd Font" -p "query:")

# Exit if none chosen.
[ -z "$request" ] && exit

urlencode() {
    # urlencode <string>
    old_lc_collate=$LC_COLLATE
    LC_COLLATE=C

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%%%02X' "'$c" ;;
        esac
    done

    LC_COLLATE=$old_lc_collate
}

googler -V -j --url-handler=/Users/fefa4ka/.local/bin/opener $request
